import sys
import zlib
import lzma
import gzip
import bz2
import re
import collections

with open('shaders.inc', 'wt') as shaders:
    shaders.write('// Autogenerated code\n')
    shaders.write('// to change, edit the corresponding file and rerun genshadersinc.py\n\n')
    for fname in ('vertex.glsl', 'fragment_pre.glsl', 'fragment_post.glsl', 'fragment_text.glsl'):
        shaders.write('// ')
        shaders.write(fname)
        shaders.write('\n')
        with open(fname, 'rt', encoding='ascii', errors='ignore') as f:
            txt = f.read()
        varname = re.sub(r'\.', '_', fname)
        shaders.write('static const char ')
        shaders.write(varname)
        shaders.write('[] =')
        for l in txt.split('\n'):
            shaders.write('\n\t"')
            shaders.write(l)
            shaders.write('\\n"')
        shaders.write(';\nstatic const size_t ')
        shaders.write(varname)
        shaders.write('sz = sizeof(')
        shaders.write(varname)
        shaders.write(') - 1;\n\n')

